# base image which include node and all essencial things to create node backend image
FROM node:24-alpine3.22

# setting up the working dir 
WORKDIR /home/app

# copy all the files 
COPY . .

# run the command to install dependencies 
RUN npm install

# build commnad to buld the project
RUN npm run build

# run CMD start command to run the project
CMD [ "npm" ,"run", "start" ]