FROM node:24-alpine3.22

WORKDIR /home/app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile

COPY tsconfig.json .
COPY src ./src

RUN pnpm run build

CMD ["pnpm" , "start"]


